name: tdenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.2.5
  - matplotlib
  - seaborn
  - pandas=2.2.3
  - scipy
  - jupyter
  - jupyterlab
  - statsmodels
  - tqdm
  - pip
  - pip:
      - gradio
      - pybads==1.0.5